//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirstCrud.EFentityDbfirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int id { get; set; }
        public Nullable<int> sub1 { get; set; }
        public Nullable<int> sub2 { get; set; }
        public Nullable<int> sub3 { get; set; }
    }
}
